// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyrcrueflnhsdwipvyek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5cmNydWVmbG5oc2R3aXB2eWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2ODgzMjksImV4cCI6MjA1NzI2NDMyOX0.TLuN5EVCSVloQ8iDWiT-x-jiRRhSFbIqipEHX10OUNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);